version: '3.8'

services:
  web1:
    build: .
    # command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    networks:
      - backend-network

  web2:
    build: .
    # command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    networks:
      - backend-network


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    
    container_name: nginx_cms
    ports:
      - 80:80
    volumes:
      # - .:/home
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    restart: always
    networks:
      - backend-network

networks:
  backend-network:
